env:
  browser: true
  node: true
  jest/globals: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
rules:
  "no-void": off

  "@typescript-eslint/no-confusing-void-expression": off
  "@typescript-eslint/no-unsafe-argument": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/promise-function-async": off

  "react/react-in-jsx-scope": off
